---
booktitle: Proceedings of the 26th Annual Conference on Learning Theory
volume: 30
year: '2013'
shortname: COLT
start: 2013-06-12
end: 2013-06-14
published: 2013-06-13
sections:
- name: preface
  title: Preface
- name: default
  title: Regular Papers
- name: open-problem
  title: Open Problems
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: COLT-2013
month: 0
cycles: false
editor:
- given: Shai
  family: Shalev-Shwartz
- given: Ingo
  family: Steinwart
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 26th Annual Conference on Learning Theory
    Held in Princeton, NJ, USA on 12-14 June 2013

  Published as Volume 30 by the Proceedings of Machine Learning Research on 13 June 2013.

  Volume Edited by:
    Shai Shalev-Shwartz
    Ingo Steinwart

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 12--14 Jun
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v30"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v30
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Conference on Learning Theory
  url: 
  location: Princeton, NJ, USA
  dates:
  - 2013-06-12
  - 2013-06-13
  - 2013-06-14
  number: 26
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
